changelog:
  categories:
    - title: "Nouvelles fonctionnalités"
      labels:
        - "📦 Features"
        - "➕ Ajout"
    - title: "Améliorations & Corrections"
      labels:
        - "🆙 Amélioration"
        - "🔧️ Changement"
    - title: "Bugs & Optimisations"
      labels:
        - "🪲 Bug Report"
        - "✨ Fixes"
        - "⚡ Optimisation"
    - title: "Autres"
      labels:
        - "*"