name: Build

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - .gitignore
      - 'LICENSE'
      - '**.md'
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with snapshot version
        env:
          SNAPSHOT: true
          GITHUB_SHA: ${{ github.sha }}
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: "noctisui-${{ github.sha }}"
          path: builds/