name: "Milestone Verification"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, assigned, demilestoned, milestoned,
             ready_for_review]

jobs:
  milestone-verif:
    name: "Verify Milestone"
    runs-on: ubuntu-latest
    steps:
      - name: Verify that PR has been assigned to a milestone
        run: |
          if [[ -z "${{ github.event.pull_request.milestone }}" ]]; then
            echo "This pull request must be assigned to a milestone."
            exit 1
          fi